stages:
  - lint
  - format
  - type_check
  - test

lint:
  stage: lint
  image: python:3.12
  script:
    - echo "Lint stage"

format:
  stage: format
  image: python:3.12
  script:
    - echo "Format stage"

type_check:
  stage: type_check
  image: python:3.12
  script:
    - echo "Type check stage"

test:
  stage: test
  image: python:3.12
  script:
    - echo "Test stage"