[changelog]
header = "# Changelog"
body = """
{% for group, commits in commits | group_by(attribute="group") %}

### {{ group }}

{% for commit in commits %}

* {{ commit.message }}
  {% endfor %}
  {% endfor %}
  """

[git]
conventional_commits = true
